package com.gaboj1.tcr.datagen.loot;

import com.gaboj1.tcr.block.TCRModBlocks;
import com.gaboj1.tcr.item.TCRItems;
import net.minecraft.data.loot.LootTableSubProvider;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

import java.util.function.BiConsumer;

public class TCRChestLootTables implements LootTableSubProvider {
    @Override
    public void generate(BiConsumer<ResourceLocation, LootTable.Builder> builder) {

        builder.accept(TCRLoot.ENTER_REALM_OF_THE_DREAM, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
//                        .add(LootItem.lootTableItem(TCRModBlocks.DENSE_FOREST_SPIRIT_FLOWER.get()).setWeight(1)).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 2.0F)))
                )
        );

        builder.accept(TCRLoot.VILLAGE1USUAL, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.DREAMSCAPE_COIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 16.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.CATNIP.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.DREAM_TA.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.BEER.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.BLUE_BANANA.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.GREEN_BANANA.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.PINE_CONE.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.JUICE_TEA.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.DRINK1.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.DRINK2.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.COOKIE.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
        );

        builder.accept(TCRLoot.VILLAGE1SPECIAL1, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.DREAMSCAPE_COIN_PLUS.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 2.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.DREAMSCAPE_COIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 16.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.RED_WINE.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.ELDER_CAKE.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 5.0F))
                        .add(LootItem.lootTableItem(TCRItems.GREEN_BANANA.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.SPYGLASS)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(Items.GOLD_INGOT)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 8.0F)))
                )

        );

        builder.accept(TCRLoot.VILLAGE1SPECIAL2, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.ORICHALCUM_BOOTS.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.ORICHALCUM_LEGGINGS.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.ORICHALCUM_CHESTPLATE.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.ORICHALCUM_HELMET.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.RAW_ORICHALCUM.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 8.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 3.0F))
                        .add(LootItem.lootTableItem(TCRItems.AMMO.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 6.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.ORICHALCUM.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 2.0F)))
                )
        );

        builder.accept(TCRLoot.TREE_HOUSE, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.DREAMSCAPE_COIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 16.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 5.0F))
                        .add(LootItem.lootTableItem(TCRItems.BASIC_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 16.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.INTERMEDIATE_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 8.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.ADVANCED_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 4.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.SUPER_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.EDEN_APPLE.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.BLUE_BANANA.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.GREEN_BANANA.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 5.0F))
                        .add(LootItem.lootTableItem(Items.APPLE)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 5.0F))
                        .add(LootItem.lootTableItem(TCRModBlocks.DENSE_FOREST_SPIRIT_TREE_LEAVES.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
        );

        builder.accept(TCRLoot.BOSS1_TOWER_TOP, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.DREAMSCAPE_COIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 16.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.DREAMSCAPE_COIN_PLUS.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 2.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(Items.DIAMOND)).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 5.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.ADVANCED_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 4.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.SUPER_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
        );

        builder.accept(TCRLoot.BOSS1TOWER, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.DREAMSCAPE_COIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 16.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 5.0F))
                        .add(LootItem.lootTableItem(TCRItems.BASIC_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 16.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.INTERMEDIATE_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 8.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 5.0F))
                        .add(LootItem.lootTableItem(TCRModBlocks.DENSE_FOREST_SPIRIT_TREE_LOG.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 16.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.SUPER_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.EDEN_APPLE.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.GOLD_INGOT)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.DIAMOND)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.NETHERITE_INGOT)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.IRON_INGOT)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.LILY_OF_THE_VALLEY)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.APPLE)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.BONE)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.PLAYER_HEAD)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(Items.SADDLE)).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.CATNIP.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRModBlocks.CATNIP.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(TCRItems.HEALTH_WAND.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(0.0F, 1.0F)))
                )
        );

        builder.accept(TCRLoot.BOSS1TREETOP, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.COPY_RESIN.get())).apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 5.0F))
                        .add(LootItem.lootTableItem(TCRItems.SUPER_RESIN.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 3.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(0.0F, 2.0F))
                        .add(LootItem.lootTableItem(Items.DIAMOND)).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 5.0F)))
                )
        );

        builder.accept(TCRLoot.ALTAR1, LootTable.lootTable()
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRModBlocks.DENSE_FOREST_SPIRIT_FLOWER.get())).apply(SetItemCountFunction.setCount(UniformGenerator.between(1.0F, 2.0F)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(1.0F, 1.0F))
                        .add(LootItem.lootTableItem(TCRItems.WITHERING_TOUCH.get())).apply(SetItemCountFunction.setCount(ConstantValue.exactly(1)))
                )
                .withPool(LootPool.lootPool().setRolls(UniformGenerator.between(2.0F, 6.0F))
                        .add(LootItem.lootTableItem(Items.GOLD_INGOT))
                )
        );

    }
}
